language: ruby
rvm:
  - 2.0.0
before_script:
  - cp config/database.yml.example config/database.yml
  - cp config/secrets.yml.example config/secrets.yml
  - bin/rake db:schema:load RAILS_ENV=test
script: xvfb-run bin/rspec spec/
